### ISSUE TITLE
Can't resolve 'p5.js-speech/lib/p5.speech in '.../node_modules/voxlens/dist'

### ISSUE THREAD

**Issue by ghost** [athersharif/voxlens#3]
Currently when trying to utilize `voxlens` anywhere in a React project, specifically with this import statement `import voxlens from "voxlens"` I am unable to actually utilize it. I keep being met with the following error: `Can't resolve 'p5.js-speech/lib/p5.speech in '.../node_modules/voxlens/dist'.`

I've attempted to install various `p5` libraries, but to no help. Was wondering if this was a known issue, if I've made a mistake, or if there's a work-around for it?

**Comment by athersharif** [comment]
@aleenaloves thanks for reporting the issue. fixed via https://github.com/athersharif/voxlens/commit/447b7b5d86d9a3b5b7be7896c02e3480e100f122 and released in https://github.com/athersharif/voxlens/releases/tag/1.2.0. please update the `voxlens` version in your package.json file to `1.2.0` and run `npm i` to update the node modules.

**Comment by ghost** [comment]
Thank you! That got rid of the error I was seeing before, but now i'm running into a new issue. This probably has to do with a mistake on my part in how to implement the voxlens feature.

Currently i'm using this library for ChartJS (https://react-chartjs-2.js.org/) - all this should be doing is taking care of the canvas creation and handling, so it shouldn't cause issue with it being used with voxlens. 

This is my code for initiating the voxlens:

```javascript
voxlens(
    "chartjs",
    document.getElementById("chart"),
    MapDataToMappedData(graphData),
    voxlensOptions
  )
```

This is my code for the voxlensOptions:
```javascript
{
    x: "month",
    y: "chickens",
    title: "number of chickens saved by month"
  })
```

This is what my MappedData looks like:
```javascript
[{
    "month": "Jul",
    "chickens": 6
}, ...]
```

And this is the error i'm currently getting:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/55119766/178295717-cef50ab4-f7c3-4030-a1e1-661b69100a5e.png">

Image Description: Errors in the console from the p5 library, also pasted in text form below:
`p5.js says: 
[bundle.js, line 207996] The property of null can't be read. In javascript the value null indicates that an object has no value.`

`Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at generateInstructions (utils.js:106:1)
    at run (index.js:190:1)
    at voxlens (index.js:205:1)`

I'm currently messing with it on my end as well, but since it had to do with the p5.js library, i didn't want to rule out anything that may have been changes from this PR as well.

**Comment by athersharif** [comment]
@aleenaloves: three quick things:

- can you share the html/jsx where you're calling the element?
- are you able to share the code with me somehow? i can take a quick look at the setup and summarize it here for anyone else running into the same issue.
- have you taken a look at the examples? (https://github.com/athersharif/voxlens/tree/main/example)

**Comment by ghost** [comment]
Yeah of course ! Thank you for being so responsive :) 

`can you share the html/jsx where you're calling the element?`

Here's the JSX file
```javascript
import { useState } from "react";
import { HTMLSelect } from "@blueprintjs/core";
import { Chart as ChartJS } from "chart.js/auto";
import { Chart, Line } from "react-chartjs-2";
import GRAPH_TYPES from "../models/GraphType.json";
import { Graph } from "./pieces/graphs";
import voxlens from "voxlens";

export const GraphPage = () => {
  const [graphType, setGraphType] = useState(0);
  const [graphData, setGraphData] = useState({
    labels: ["Jun", "Jul", "Aug"],
    datasets: [
      {
        id: 1,
        label: "Number of Chickens Saved",
        data: [5, 6, 7],
      },
    ],
  });
  const [voxlensOptions, setVoxlensOptions] = useState({
    x: "month",
    y: "chickens",
    title: "number of chickens saved by month"
  });

  voxlens(
    "chartjs",
    document.getElementById("chart"),
    MapDataToMappedData(graphData),
    voxlensOptions
  )

  return (
    <div style={{ margin: 10 }}>
      <div>
        <span>
          Select Graph Type:{" "}
          <HTMLSelect
            onChange={(e) => setGraphType(GRAPH_TYPES[e.target.value])}
            options={Object.keys(GRAPH_TYPES)}
          />
        </span>
      </div>
      <Graph id="chart" data={graphData} type={graphType} />
    </div>
  );
};

function MapDataToMappedData(data) {
  let mappedData = [];
  data.labels.forEach((label, index) => {
    let item = { month: label, chickens: data.datasets[0].data[index] };
    mappedData.push(item);
  });
  console.log(mappedData);
  return mappedData;
}
```

and all of the graphs are mapped like this in the `react-chartjs-2` package
```typescript
export declare const Line: <TData = (number | import("chart.js").ScatterDataPoint | null)[], TLabel = unknown>(props: Omit<ChartProps<"line", TData, TLabel>, "type"> & {
    ref?: import("./types").ForwardedRef<ChartJSOrUndefined<"line", TData, TLabel>> | undefined;
}) => JSX.Element;
```

`are you able to share the code with me somehow? i can take a quick look at the setup and summarize it here for anyone else running into the same issue.`

^^ That's all the relevant code, I can share the repo with you too if you'd like. I'm currently testing a host of accessibility tools made for the mathematical context and wanted to test voxlens out with more complex examples to see where we're currently at. 

`have you taken a look at the examples? (https://github.com/athersharif/voxlens/tree/main/example)`
And yeah! I tried to follow the example to the best of my ability, but of course there's still room for error.

**Comment by athersharif** [comment]
thanks, that's helpful! if you're able to share the repo, i can dig deeper into it. also, as a quick check, can you double check to see if the `id` prop on `Graph` is being passed on to the underlying component?

**Comment by ghost** [comment]
Thank you Ather! What ended up being the issue was that the canvas was being drawn after the `voxlens` initialization, so it didn't have a chart to grab onto. Was able to fix it - my fix was quite hacky, but it worked in my case with the library i was using. Pasting here if it helps you with other people in the future - and thanks again for all your help :) 

<img width="509" alt="image" src="https://user-images.githubusercontent.com/55119766/178752354-5f11ab90-73a3-440e-bf58-9790a442fe3b.png">
